# I am sorry, but you have to input your own user-agent, we don't provide it.
# (so that ban by improper use of this software won't affect all other users).
# Base on VocaDB Admin's advice, it's better to provide your VocaDB username
userAgent: ""